# Generated by Django 5.1.4 on 2024-12-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_bookingride_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingride',
            name='chat',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
