# Generated by Django 5.1.4 on 2024-12-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='range_in_km',
        ),
        migrations.AddField(
            model_name='ride',
            name='going_from_within',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='going_to_within',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
